exports.CONSTANTS = {
    'TOKEN_REQUIRED': 'Missing token, required token',
    'INVALID_TOKEN':'Invalid token',
    'MORE_USER_WITH_SAME_LOGIN':'More than one user found with provided login!',
    'INVALID_PASSWORD_OR_LOGIN':'Make sure you provided correct login and password',
    'LOGIN_TAKEN':'Login is already taken by other user',
    'EMAIL_TAKEN':'Provided email already taken',
    'ALREADY_SIGN_IN':"Znaleziono konto o takich danych. Zapisz się na prelekcje z poziomu konta",
    'NO_FREE_SEATS':'No more seats left in lecture',
    'NEW_USER':'Succesful sign in for lecture, to manage your account pls login in',
    'NO_USER_WITH_LOGIN':'No user found with provided login',
    'USER_ALREADY_BUSY_AT_THIS_TIME':'User is already sign in on other lecture at this time',
    'SUCCESS_LECTURES_SIGN_IN':'Succesfuly sign in for lecture',
    'ERROR_CANCEL_RESERVATION':'Something went wrong during cancel reservation',
    'SUCCESS_CANCEL_RESERVATION': "Cancel reservation successful",
    'EMAIL_UPDATE':'Succesfuly updated email',
  }